---
# to run pre-commit on demand using below configuration:
# pre-commit run --all-files

# default_language_version:
#   python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^tests
      - id: trailing-whitespace
        exclude: ^tests
      - id: check-added-large-files
        args: ["--maxkb=1000"]
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        language: system
        entry: yamllint
        args:
          [
            "-d {extends: default, rules: {line-length: {max : 120}, truthy: disable}}",
            "-s",
          ]
        exclude: ^.github/
