name: webhook
on:
  workflow_dispatch:
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Input 1: ${{ github.event.inputs.input1 }}"
          echo "Input 2: ${{ github.event.inputs.input2 }}"