name: webhook
on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input 1'
        required: true
        default: 'default value'
      input2:
        description: 'Input 2'
        required: true
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Input 1: ${{ github.event.inputs.input1 }}"
          echo "Input 2: ${{ github.event.inputs.input2 }}"