name: webhook
on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Payload data'
        required: true
        default: {}
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Input 1: ${{ github.event.inputs.data | fromJson}}"
